### ISSUE TITLE
Exception when connecting Stripe Connect account

### ISSUE THREAD

**Issue by jaydensmith** [enupal/stripe#158]
```
yii\base\UnknownPropertyException: Setting unknown property: enupal\stripe\elements\Vendor::testmode in /Users/jaydensmith/public_html/site.com/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/jaydensmith/public_html/site.com/vendor/craftcms/cms/src/base/Element.php(1454): yii\base\Component->__set('testmode', '1')
#1 /Users/jaydensmith/public_html/site.com/vendor/enupal/stripe/src/controllers/UtilitiesController.php(80): craft\base\Element->__set('testmode', '1')
#2 [internal function]: enupal\stripe\controllers\UtilitiesController->actionAuthorizeOauth()
#3 /Users/jaydensmith/public_html/site.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Users/jaydensmith/public_html/site.com/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#5 /Users/jaydensmith/public_html/site.com/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('authorize-oauth', Array)
#6 /Users/jaydensmith/public_html/site.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('authorize-oauth', Array)
#7 /Users/jaydensmith/public_html/site.com/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('enupal-stripe/u...', Array)
#8 /Users/jaydensmith/public_html/site.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('enupal-stripe/u...', Array)
#9 /Users/jaydensmith/public_html/site.com/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#10 /Users/jaydensmith/public_html/site.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /Users/jaydensmith/public_html/site.com/public_html/index.php(21): yii\base\Application->run()
#12 /Users/jaydensmith/.composer/vendor/weprovide/valet-plus/server.php(131): require('/Users/jaydensm...')
#13 {main}
```

**Comment by andrelopez** [comment]
Hi @jaydensmith  We just released Stripe Payments v3.2.3 with a fix to this issue. Thanks for reporting!
