### ISSUE TITLE
Error while accessing the Tax tab

### ISSUE THREAD

**Issue by romainpoirier** [enupal/stripe#222]
### Description

```
yii\base\ErrorException: Undefined variable: tax in /vendor/enupal/stripe/src/services/Taxes.php:40
Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/...', 40)
#1 /vendor/enupal/stripe/src/services/Taxes.php(40): craft\web\ErrorHandler->handleError(8, 'Undefined varia...', '/...', 40, Array)
#2 /vendor/twig/twig/src/Extension/CoreExtension.php(1511): enupal\stripe\services\Taxes->getAllTaxes()
#3 /vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(enupal\stripe\services\Taxes), 'getAllTaxes', Array, 'method', false, false)
#4 /storage/runtime/compiled_templates/f9/f9a53a267b08df5cc19c1c0c620c747582d52343d838bb72019442f1ea18e195.php(45): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(enupal\stripe\services\Taxes), 'getAllTaxes', Array, 'method')
#5 /vendor/twig/twig/src/Template.php(405): __TwigTemplate_218bbf6646baa206d83ef49505282319c0e613f87e9dee199c25498f2009b0d1->doDisplay(Array, Array)
#6 /vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#8 /vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#9 /vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#10 /vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('enupal-stripe/t...', Array)
#11 /vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('enupal-stripe/t...', Array)
#12 /vendor/craftcms/cms/src/web/Controller.php(256): craft\web\View->renderPageTemplate('enupal-stripe/t...', Array, 'cp')
#13 /vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('enupal-stripe/t...', Array)
#14 [internal function]: craft\controllers\TemplatesController->actionRender('enupal-stripe/t...', Array)
#15 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#17 /vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('render', Array)
#18 /vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('render', Array)
#19 /vendor/craftcms/cms/src/web/Application.php(277): yii\base\Module->runAction('templates/rende...', Array)
#20 /vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('templates/rende...', Array)
#21 /vendor/craftcms/cms/src/web/Application.php(262): yii\web\Application->handleRequest(Object(craft\web\Request))
#22 /vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /htdocs/index.php(26): yii\base\Application->run()
#24 {main}
```

### Steps to reproduce

1. Go to `/admin/enupal-stripe/tax`

### Additional info

- Craft version: 3.7.16
- PHP version: 7.4.14
- Database driver & version: MySQL 5.7.32
- Plugin version: 1.4.20
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?: Yes

**Comment by andrelopez** [comment]
Hi @romainpoirier thanks for reporting this issue. We just released a fix on v3.3.8
